spring.application.name=practice
# Expose all actuator endpoints
management.endpoints.web.exposure.include=*

# Show health details
management.endpoint.health.show-details=always

# Enable Prometheus metrics
management.prometheus.metrics.export.enabled=true
